version: '3'

services:
    laravel:
      build: 
        context: ./Docker-Laravel
        dockerfile: Dockerfile.prod
      image: pedroalmeida92/laravel:prod
      container_name: laravel
      networks: 
        - laranet
    
    nginx:
      build: 
        context: ./FirstDockerFile
        dockerfile: Dockerfile.prod
      image: pedroalmeida92/nginx:prod
      container_name: nginx
      networks: 
        - laranet
      ports: 
        - "8080:80"

networks: 
  laranet
    driver: bridge